import type { NextPage } from "next"
import Head from "next/head"
import React from "react"

const Post: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Instagram Clone Post Page</title>
        <meta name="description" content="Generated by create next app" />{" "}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Post page </div>
      </main>
    </div>
  )
}
// async function getStaticProps() {
//   const { data } = await client.query({
//     query: gql`
//       query Countries {
//         countries {
//           code
//           name
//           emoji
//         }
//       }
//     `,
//   });

//   return {
//     props: {
//       countries: data.countries.slice(0, 4),
//     },
//  };
// }
export default Post
